Dev
ClemDSC/playerbook pull request #11
Opened 2022-10-21 12:30 UTC by ClemDSC

2022-10-21 12:47 UTC, peacepilou commented on src/app/components/landing-page/site-description/site-description.component.html
> +<h2 class="h2-description">Envie de partager ?</h2>
identation

2022-10-21 12:50 UTC, peacepilou commented on src/app/components/navbar/navbar.component.html
> +      src="../../assets/pictures/logo-home-gamepad.png"
/assets devrait suffire

2022-10-21 12:51 UTC, peacepilou commented on src/app/components/navbar/navbar.component.html
> +  <div class="list-navigation">
Si temps : à refactor

2022-10-21 12:55 UTC, peacepilou commented on src/app/components/user-card/user-card.component.html
> +      <div class="profile--body">
sauter une ligne avant et après le body

2022-10-21 12:56 UTC, peacepilou commented on src/app/components/user-card/user-card.component.ts
> +  @Input() userCardChild:User = new User(0, "", "", "", "", new UserBehavior(true, true, true, true, ""), new PlayerHabit(0, true, 0, true, true, true, true),
espace entre le : et le type

2022-10-21 12:57 UTC, peacepilou commented on src/app/components/user-list/user-list.component.ts
> +  userList: any[] = [];
À typer

2022-10-21 12:58 UTC, peacepilou commented on src/app/components/user-list/user-list.component.ts
> +          .map((game: { userPseudo: any }) => game.userPseudo)
à typer

2022-10-21 13:03 UTC, peacepilou commented on src/app/shared/user-http.service.ts
> +    return this.userHttp.get<any>(`${this.baseUrl}`);
à typer tous les any

2022-10-21 13:05 UTC, peacepilou commented on src/models/landing-button.model.ts
> +        public id : number,
pas d'espace avant les " : "

2022-10-21 13:06 UTC, peacepilou commented on src/models/user.model.ts
> +        public userBehaviorList: UserBehavior,
renommer : enlever le "List" à la fin

2022-10-21 13:07 UTC, peacepilou requested changes
Bien joué on est y presque

2022-10-21 13:37 UTC, ClemDSC reviewed
requested changes done

2022-10-21 15:00 UTC, ClemDSC reviewed
Changes done

2022-10-24 08:08 UTC, peacepilou approved these changes
gg

2022-10-24 08:08 UTC, merged